### ISSUE TITLE
Keeping part number

### ISSUE THREAD

**Issue by veleda** [Sjofartsdirektoratet/NLP_PoC#10]
### Example from regulation
Section 24. Emergency source of power and emergency lighting, etc.
(1) Vessels of 10.67 to 15 metres in overall length constructed after 1 January 1992 shall have an emergency
source of power providing satisfactory lighting for at least 2 hours to:
a) lighting in areas with life-saving appliances and launching arrangements;
b) lighting in alleyways, stairways and exits to the life-saving appliances and of the sea where the life-saving
appliances are launched;
c) necessary navigation lights; and
d) required alarm system.

### Information to keep
* Section 24 --> Paragraph number
* (1) --> Part
* a), b), c) & d) --> Sub-part

### Example of output
All of these shall be kept in output CSVs as own columns. E.g.:

`Section 24, 1, a, info, info, info`
`Section 24, 1, b, info, info, info`

**Comment by veleda** [comment]
Empty fields (e.g. missing sub-part enumeration) described as `none`.

**Comment by cZTHpWPnN** [comment]
The result of this component must still be implemented in other components, and all components must be refactored and get new chapter text input with the right format.
