### ISSUE TITLE
Identify chapter and section in text

### ISSUE THREAD

**Issue by veleda** [Sjofartsdirektoratet/NLP_PoC#22]
Need to extract:

regulation number
headline-chapter: chapter number, chapter title
headline-section: section number, section title

Example:
regulation number: 1404
headline-chapter: 3, Fire, machinery and electric installations
headline-section: 8, Fire safety

**Comment by cZTHpWPnN** [comment]
Regulation number is not to be found in a selected chapter.

**Comment by veleda** [comment]
@cZTHpWPnN Let's wait with regulation number, and focus on chapter and section. 😄

**Comment by cZTHpWPnN** [comment]
This is solved now. Documentation: https://sdir.atlassian.net/wiki/spaces/SDIR/pages/1145896992/identify-chapter-and-section-in-chapter-text
