### ISSUE TITLE
Identify pretrained models

### ISSUE THREAD

**Issue by veleda** [Sjofartsdirektoratet/NLP_PoC#29]
Do there exist pretrained model in Norwegian bokmål?

**Comment by mirimurr** [comment]
Norwegian:
Spacy
https://github.com/web64/spacy-norwegian - Train norwegian models for Spacy
https://github.com/jarib/spacy-nb - Scripts to build a Norwegian model for spacy
https://github.com/ohenrik/nb_news_ud_sm - Experimental Norwegian (Bokmål) language model for Spacy (Including NER)
https://github.com/ohenrik/nb_dep_ud_sm - Experimental Norwegian (Bokmål) language model for Spacy
https://github.com/navikt/ai-lab-spacy-bokmaal - Norwegian model for spaCy
Bert:
BERT
https://github.com/NBAiLab/notram - NoTraM - Norwegian Transformer Mode
http://wiki.nlpl.eu/Vectors/norlm/norbert - NorBERT: Bidirectional Encoder Representations from Transformers
https://github.com/botxo/nordic_bert - Nordic BERT: Norwegian Model: (Trained on 4.5gb text)
NER:
https://github.com/ljos/navnkjenner - Named-Entity Recognition for Norwegian Bokmål and Nynorsk
