### ISSUE TITLE
Scopes

### ISSUE THREAD

**Issue by veleda** [Sjofartsdirektoratet/NLP_PoC#30]
:white_check_mark: Discuss findings with Kristian and Arild.

All local names are under the namespace `https://www.sdir.no/SDIR_Simulator`

Scopes marked with :heavy_exclamation_mark: is awaiting its own sub-ontology.

### List of scopes

- [x] Gross tonnage 
- [x] Built date
- [x] Voltages
- [x] Vessel
- [x] Vessel type
- [x] Trade area
- [x] Flashpoint
- [x] Mobile unit
- [x] Propulsion power
- [x] Keel laid
- [x] Cargo
- [x] Loading and unloading installation
- [x] Length (L)
- [x] Conversion
- [x] Passengers
- [ ] Period
- [x] Radio area
- [ ] Certificate
- [x] Vessel length overall (LOA)
- [x] Protected

### Abbreviations

| r | c | s | p | sp |
|--|--|--|--|--|
| regulation | chapter | section | part | sub-part |

**Comment by veleda** [comment]
## Gross tonnage
### Expected output

| regulation no. | chapter no. | section no. | part no. | sub-part no. | context | value 1 | value 2 | metric |
| ------------- |-------------| -------------| -------------| -------------| -------------| -------------| -------------| -------------| 
| 1523 | 4 | 23a | 1 | | under | 500 | | GT |
| 1523 | 4 | 26 | 1 | b | opp til | 3000 | | GT |
| 1523 | 4 | 26 | 3 |  | eller mer | 500 | | GT |
| 1072 | 4 | 26 | 3 |  | eller over | 500 | | GT |

### Examples from regulation
* 1523, ch. 4, §26 1) b): overstyrmann på skip med **bruttotonnasje opp til 3000** i ubegrenset fartsområde.
* 1523, ch. 4, §26 2): skip med **bruttotonnasje under 500**

**Comment by veleda** [comment]
## Built date
Predicate: `builtDate`
Domain: `Ship`
Range: `xsd:date`

### Expected output

| r | c | s | p | sp | context | value 1 | value 2 | metric |
| ------------- |-------------| -------------| -------------| -------------| -------------| -------------| -------------| -------------| 
| 1404 | 3 | 7 | 2 | | før | 2. januar 1988 | | xsd:date |
| 1404 | 3 | 8 | 1 |  | etter | 1. januar 1992 | | xsd:date |
| 1404 | 4 | 26 | 2 |  | mellom | 1. januar 1992 | 1. januar 2015 | xsd:date |

| r | c | s | p | sp | context | value 1 | value 2 | metric |
| ------------- |-------------| -------------| -------------| -------------| -------------| -------------| -------------| -------------| 
| 1404 | 3 | 7 | 2 | | before | 2 January 1988 | | xsd:date |
| 1404 | 3 | 8 | 1 |  | after | 1 January 1992 | | xsd:date |
| 1404 | 4 | 26 | 2 |  | between | 1 January 1992 | 1 January 2015 | xsd:date |

### Examples from regulation
| Lang | Position | Text |
|---|---|---|
| no | 1404/3/7/2 | Fartøy som er bygget **før 2. januar 1988** skal være bygget og utrustet etter |
| en | 1404/3/7/2 | Vessels constructed **before 2 January 1988** shall be constructed and equipped in |
| no | 1404/3/8/1 | Fartøy bygget **etter 1. januar 1992** skal brannsikres konstruksjonsmessig |
| en | 1404/3/8/1 | Vessels constructed **after 1 January 1992** shall have structural fire protection |
| no | 1404/4/26/2 |  For fartøy med største lengde 6 til 10,67 meter bygget **mellom 1. januar 1992 og 1. januar 2015** skal |
| en | 1404/4/26/2 |  For vessels of 6 to 10.67 metres in overall length constructed **between 1 January 1992 and 1 January 2015** the stability |

### Example shape
This is the expected final output from RDF transformation. 
```
:PS_BuiltDate_b19920101
    a sh:PropertyShape, sdir:Scope ;
    sh:description "Virkeområde byggeår før 1. januar 1992."@no, 
                   "Scope of built date before Janury 1st 1992."@en ;
    sh:path sdir:builtDate ;
    sh:maxExclusive "1992-01-01" ;
    sh:datatype xsd:date.
```

**Comment by veleda** [comment]
## Voltages
Predicate: `voiltages`
Range: `unit:V`

### Expected output

| r | c | s | p | sp | context | value 1 | value 2 | metric |
| ------------- |-------------| -------------| -------------| -------------| -------------| -------------| -------------| -------------| 
| 1404 | 3 | 23 | 1 | | inntil | 50 | | unit:V |
| 1404 | 3 | 23 | 3 |  | over | 50 | | unit:V |

| r | c | s | p | sp | context | value 1 | value 2 | metric |
| ------------- |-------------| -------------| -------------| -------------| -------------| -------------| -------------| -------------| 
| 1404 | 3 | 23 | 1 | | up to | 50 | | unit:V |
| 1404 | 3 | 23 | 3 |  | more than | 50 | | unit:V |

### Examples from regulation
| Lang | Position | Text |
|---|---|---|
| no | 1404/3/23/1 | Fartøy med største lengde 6 til 15 meter bygget etter 1. januar 1992 med elektriske anlegg med **spenning inntil 50 V** skal |
| en | 1404/3/23/1 | Vessels of 6 to 15 metres in overall length constructed after 1 January 1992 with electrical installations with **voltages of up to 50 V** shall |
| no | 1404/3/23/3| Fartøy med største lengde 6 til 15 meter bygget mellom 1. januar 1992 og 2002 med elektrisk anlegg med **spenning over 50 V** skal |
| en | 1404/3/23/3 | Vessels of 6 to 15 metres in overall length constructed between 1 January 1992 and 2002 with electrical installations with **voltages of more than 50 V** shall |

### Example shape
This is the expected final output from RDF transformation. 
```
scope:PS_V_max_50 a sh:PropertyShape, scope:Scope;
  sh:description "Virkeområde elektriske innstallasjoner opp til 50 V."@no, "Scope of electrical installations up to 50 V."@en;
  sh:path sdir:voltages;
  sh:maxExclusive "50";
  sh:datatype unit:V .
```

**Comment by veleda** [comment]
## Vessel type
Predicate: `vesselType`

### Expected output

| r | c | s | p | sp | context | value 1 | value 2 | metric |
| ------------- |-------------| -------------| -------------| -------------| -------------| -------------| -------------| -------------| 
| 1853 | 1 | 1 | 1 | | lasteskip |  | | |
| 1574 | 1 | 1 | 1 |  | hurtiggående passasjerfartøy | | | |

For norsk er dette termer som slutter på *-båt*, *-skip*, *-fartøy*.

| r | c | s | p | sp | context | value 1 | value 2 | metric |
| ------------- |-------------| -------------| -------------| -------------| -------------| -------------| -------------| -------------| 
| 1853 | 1 | 1 | 1 | | cargo ship |  | | |
| 1573 | 1 | 1 | 1 |  | passenger high-speed craft |  | |  |

### Examples from regulation
| Lang | Position | Text |
|---|---|---|
| no | 1853/1/1/1 | Forskriften gjelder for norske **lasteskip** med |
| en | 1853/1/1/1 | These Regulations apply to Norwegian **cargo ships** of |
| no | 1574/1/1/1 | Denne forskriften gjelder for nye og eksisterende norske **hurtiggående passasjerfartøy** med lengde |
| en | 1574/1/1/1 | These Regulations apply to any new and existing Norwegian **passenger high-speed craft** of less than |

### Example shape
This is the expected final output from RDF transformation. 
```
:PS_FishingVessel 
    a sh:PropertyShape, sdir:Scope ;
    sh:description "Virkeområde fiskefartøy."@no, 
                   "Scope of fishing vessels."@en ;
    sh:path sdir:vesselType ;
    sh:hasValue sdir:FishingVessel .
```

**Comment by veleda** [comment]
## Trade area
Predicate: `tradeArea`

TBW

**Comment by veleda** [comment]
## Flashpoint
Predicate: `flashpoint`

TBW

**Comment by veleda** [comment]
## Mobile unit
Predicate: `mobileUnit`

TBW

**Comment by veleda** [comment]
## Propulsion
Predicate: `propulsion`

TBW

**Comment by veleda** [comment]
## Propulsion effect
Predicate: `propulsionEffect`

TBW

**Comment by veleda** [comment]
## Keel laid
Predicate: `keelLaid`

TBW

**Comment by veleda** [comment]
## Heeling moment
Predicate: `heelingMoment`

TBW

**Comment by veleda** [comment]
## Cargo
Predicate: `cargo`

TBW

**Comment by veleda** [comment]
## Loading and unloading installation
Predicate: `loadingUnloadingInstallation`

TBW

**Comment by veleda** [comment]
## Length (L)
Predicate: `length`

TBW

**Comment by veleda** [comment]
## Conversion
Predicate: `conversion`

TBW

**Comment by veleda** [comment]
## Passengers
Predicate: `passengers`

TBW

**Comment by veleda** [comment]
## Radio area
Predicate: `radioArea`

TBW

**Comment by veleda** [comment]
## Vessel length overall (LOA)
Predicate: `vesselLengthOverall`

TBW

**Comment by veleda** [comment]
## Protected
Predicate: `protected`

TBW

**Comment by cZTHpWPnN** [comment]
Discovery: Norwegian law text contain DATE that sometimes is just a year. Example:
```
                {
                    "referenceId": "/kapittel/3/paragraf/23/ledd/3",
                    "content": "(3) Fartøy med største lengde 6 til 15 meter bygget mellom 1. januar 1992 og 2002 med elektrisk anlegg med spenning over 50 V skal tilfredsstille kravene fastsatt i den nå opphevede forskrift 1. mars 1990 nr. 125 for elektriske anlegg - Maritime installasjoner.",
                    "subparts": [],
                    "sentences": [],
                    "uid": "3d6b9bd9-dd60-4957-b12d-08d8c4369707",
                    "url": "/regulation/2013/11/22/1404/chapter/3/section/23/part/3"
                },
```
