### ISSUE TITLE
Create dataset and guidelines for annotation

### ISSUE THREAD

**Issue by mirimurr** [Sjofartsdirektoratet/NLP_PoC#31]
Extract text and transform into a suitable format.
1853
1404
1072
0878
1019
3793
1893

**Comment by veleda** [comment]
First and second iteration in English done. 
First iteration in Norwegian ongoing.

**Comment by mirimurr** [comment]
Currently correction Norwegian annotations. Will start correcting English annotations this week after manual cleaning of dataset.
