### ISSUE TITLE
Identifisere alternative referanser

### ISSUE THREAD

**Issue by veleda** [Sjofartsdirektoratet/NLP_PoC#5]
Førstepri:
Finne f.eks: _Regulations of 20 October 1983 No. 1580_
Ta vare på kapittelnr og paragrafnr.

Andre pri:
Finne: _C14 of Nordic Boat Standard (1990)_
Ta vare på kapittelnr og paragrafnr.

**Comment by veleda** [comment]
Note to self: legge inn tabelleksempel.

**Comment by cZTHpWPnN** [comment]
Done. Doc: https://sdir.atlassian.net/wiki/spaces/SDIR/pages/1264615425/identify-alternative-reference-in-text-service-norwegian-chapter-input
