### ISSUE TITLE
How to empty dev-workflow in EDG

### ISSUE THREAD

**Issue by veleda** [Sjofartsdirektoratet/NLP_PoC#51]
Investigate how the flow in TopBraid EDG works in practise. 

1. Push RDF to a dev-workflow
2. Do manual QA of graph
3. Empty dev-workflow and push to prod-workflow

**Comment by cZTHpWPnN** [comment]
https://www.youtube.com/watch?v=AtdKdixL1R4 --> Quick Grok Video: Intro to Workflows in TopBraid EDG

**Comment by cZTHpWPnN** [comment]
Issue when testing #56

**Comment by cZTHpWPnN** [comment]
Test completed successfully.
