### ISSUE TITLE
TopBraid EDG / nginx 504 Gateway Time-out issue

### ISSUE THREAD

**Issue by cZTHpWPnN** [Sjofartsdirektoratet/NLP_PoC#56]

**Comment by veleda** [comment]
Lars tar det opp med Fosli

**Comment by cZTHpWPnN** [comment]
Fosli har fiksa. Ventar med å lukke denne til at fiksen er klar for testing og sjekk at det funka i praksis.

**Comment by cZTHpWPnN** [comment]
Pull request completed by Fosli: https://dev.azure.com/sdir-no/Core/_git/Core/pullrequest/2597

**Comment by cZTHpWPnN** [comment]
Issue is resolved and tested.
