### ISSUE TITLE
Discovering scopes

### ISSUE THREAD

**Issue by veleda** [Sjofartsdirektoratet/NLP_PoC#6]
### Vessel length overall
Exptected output CSV must contain:
`'paragraph number', 'relation', 'value 1', 'value 2 (iff present)'`
_Example_; `'Section 15', 'to', '10.67', '15'`
_Example_; `'Section 15', 'less than', '10.67'`

Snippet from the text:
**Section 15**. Fire-extinguishing systems in machinery spaces
(1) **Vessels of 10.67 to 15 metres** in overall length shall have a fire-extinguishing system. When there are persons on board, the fire-extinguishing system shall only be capable of manual release.

### Built date
Expected output CSV must contain:
`'paragraph number', 'before/after', 'date value'`
_Example_: `'Section 22', 'after', '1 January 1992'`

Snippet from the text:
**Section 22**. Machinery and piping systems
(1) Vessels constructed **after 1 January 1992** shall satisfy the requirements of Nordic Boat Standard (1990)

### Machine power
Expected output CSV must contain:
`'paragraph number', 'relation', 'value'`
_Example_: `'Section 23', 'up to', '50'`

Snippet from the text:
**Section 23**. Electrical installations
(1) Vessels of 6 to 15 metres in overall length constructed after 1 January 1992 with electrical installations with voltages of **up to 50 V** shall satisfy the requirements of Nordic Boat Standard (1990) C11 on electrical installations.

### NB!
CSV will be produced separately for each kind of scope.

**Comment by veleda** [comment]
Current output from transformator for machine power:

```
sdir:FOR1404P23 a sdir:Requirement, sh:NodeShape;
  sdir:regulationReference "https://lovdata.no/forskrift/2013-11-22-1404/§23"^^xsd:anyURI;
  sh:property sdir:PS_MP_min50, sdir:PS_MP_max50 .

sdir:PS_MP_min50 a sh:NodeShape, sdir:Scope;
  sh:description "Scope of machine power more than 50V."@en, "Virkeområde maskinkraft mer enn 50V."@no;
  sh:minInclusive "50"^^xsd:int;
  sh:datatype unit:V;
  sh:minCount "1"^^xsd:int;
  sh:maxCount "1"^^xsd:int .

sdir:PS_MP_max50 a sh:NodeShape, sdir:Scope;
  sh:description "Scope of machine power up to 50V."@en, "Virkeområde maskinkraft opp til 50V."@no;
  sh:maxExclusive "50"^^xsd:int;
  sh:datatype unit:V;
  sh:minCount "1"^^xsd:int;
  sh:maxCount "1"^^xsd:int .
```

**Comment by cZTHpWPnN** [comment]
Nydeleg!
